### ISSUE TITLE
Using Redshift isomorphically.

### ISSUE THREAD

**Issue by ArnoBuschmann** [InventingWithMonster/redshift#55]
Hi Matt, Thanks for telling about the svg path route fix. Before checking on that, right now I'm trying to integrate Redshift wir Cycle.js (which is using virtual-dom itself) -> https://github.com/staltz/cycle.

The goal is to get an implemenation based on the isomorphic Cycle example -> https://github.com/staltz/cycle/tree/master/examples/isomorphic

Isomorphic here just means the app can render both, from the client and the server.

As Redshift is coupled with the window object because of the dom, it throws an error server side and I wonder, if there is a way to entirely decouple Redshift from the Dom so Redshift could be used also as a NPM module with isomorphic abilities?

**Comment by ArnoBuschmann** [comment]
To clarify, of course the server should not render animations, it's just about the "incompatibility" of both environments. And as you need the window object in Redshift to ask for window.requestAnimationFrame, I guess, the only way to handle it is to wrap Redshift code like this?

```javascript
if (typeof window !== "undefined") {
    var redshift = require('redshift');
    var renderAction = redshift.newAction();
    renderAction.play({
         ...
    });
}
```

**Comment by InventingWithMonster** [comment]
Hey man. Node support was actually a design goal at one point, I'd just forgotten about it recently. Redshift can be used for all sorts of number tweening, like eased iterating over an array, which could be useful for powering Arduino hardware. 

So thanks for reminding me - if you update to 1.2.0 or download the latest redshift.global.min.js, this should work with Node now.

**Comment by ArnoBuschmann** [comment]
Node support, very nice, thank you! :) Yep, after playing around with Redshift, it got clear, that receiving the tweening data itself is environment independent and useful to have everywhere.

Cycle (the links I posted above) is mainly working with RxJS streams (https://github.com/Reactive-Extensions/RxJS), they even published a small utility for tweening via RxJS yesterday -> https://github.com/staltz/rxtween

Now when thinking about it, streams (RxJS) and Redshift are, of course, a perfect match, because Redshift delivers "data over time". So my next try will be to create RxJS observables from Redshift data, which then should integrate nicely into the Cycle philosophy of "everything is a stream".

Let's see, how that'll work out ;)
